# GitHub Secrets (Must Configure)
# Go to: GitHub → Settings → Secrets → Actions

# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# AWS_REGION = ap-south-1

name: CI/CD Terraform AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2. Setup Node (for Lambda)
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # 3. Prepare Lambda package
    - name: Package Lambda
      run: |
        cd lambda
        zip -r ../lambda.zip index.js

    # 4. Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # 5. Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 6. Terraform Init
    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    # 7. Terraform Validate
    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

    # 8. Terraform Plan
    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform

    # 9. Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform