name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      s3_key:
        description: 'Lambda S3 Key'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v3

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - run: terraform init
      working-directory: terraform

    - run: terraform apply -auto-approve -var="lambda_s3_key=${{ github.event.inputs.s3_key }}"
      working-directory: terraform
